openapi: 3.0.0
info:
  title: App Details API
  version: 1.0.0
paths:
  /get-app-details/{app_id}:
    get:
      summary: Retrieve app details
      description: Retrieves the details of an app with the given ID.
      parameters:
        - name: app_id
          in: path
          description: ID of the app
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppDetailsResponse"
  /set-app-details/{app_id}:
    post:
      summary: Update or create app details
      description: Updates or creates the details of an app with the given ID.
      parameters:
        - name: app_id
          in: path
          description: ID of the app
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppDetailsRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppDetailsResponse"
components:
  schemas:
    AppDetailsRequest:
      type: object
      properties:
        url:
          type: string
        name:
          type: string
        description:
          type: string
        front_technology:
          type: string
        back_technology:
          type: string
        database_technology:
          type: string
        author:
          type: string
        github_url:
          type: string
    AppDetailsResponse:
      type: object
      properties:
        url:
          type: string
        name:
          type: string
        description:
          type: string
        front_technology:
          type: string
        back_technology:
          type: string
        database_technology:
          type: string
        author:
          type: string
        github_url:
          type: string
